name: New Hire Welcome

on:
  schedule:
    # Runs at 9:00 AM Manila time (1:00 AM UTC) every day
    - cron: '0 1 * * *'
  workflow_dispatch: # Allows manual trigger for testing

jobs:
  welcome-new-hires:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Run welcome bot
      env:
        MONDAY_API_TOKEN: ${{ secrets.MONDAY_API_TOKEN }}
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      run: |
        python welcome_bot.py
